volumes:
    pg-data:

services:
    postgres:
        image: postgres:12
        ports:
            - 5432:5432
        volumes:
            - /pg-data:/pg-data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: modeller
            PGDATA: /pg-data

    adminer:
        image: adminer
        ports:
            - 8090:8080
