name: Deploy to AWS Fargate

on:
    workflow_dispatch:
    pull_request:
        types: [closed]
        paths:
            # Only trigger when files in my-remix-app directory change
            - 'my-remix-app/**'

jobs:
    deploy:
        # Only run this job if the PR was merged (not just closed)
        # if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Authenticate with AWS
              id: authenticate
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  role-to-assume: arn:aws:iam::156041424020:role/github-oidc-role-86262ca
                  aws-region: us-east-1

            - name: Log into ECR
              run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 156041424020.dkr.ecr.us-east-1.amazonaws.com/modeller-repo-1f858f9

            - name: Build & Push Docker image
              working-directory: ./my-remix-app
              run: |
                  docker build -t modeller-repo-1f858f9:latest .
                  docker tag modeller-repo-1f858f9:latest 156041424020.dkr.ecr.us-east-1.amazonaws.com/modeller-repo-1f858f9:latest
                  docker push 156041424020.dkr.ecr.us-east-1.amazonaws.com/modeller-repo-1f858f9:latest

            - name: Install Pulumi dependencies
              run: npm ci
              working-directory: ./infra

            - name: Install Pulumi & Deploy
              uses: pulumi/actions@v6
              with:
                  command: up
                  stack-name: dev
                  work-dir: ./infra
              env:
                  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
