name: Deploy to AWS Fargate

on:
    workflow_dispatch:
    pull_request:
        types: [closed]
        paths:
            # Only trigger when files in my-remix-app directory change
            - 'my-remix-app/**'

jobs:
    deploy:
        # Only run this job if the PR was merged (not just closed)
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Authenticate with AWS
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  role-to-assume: arn:aws:iam::156041424020:role/github-oidc-role-86262ca
                  aws-region: us-east-1

            - name: Log into ECR
              run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <ECR_URI>

            - name: Build Docker image
              run: |
                  docker build -t modeller:latest .
                  docker tag modeller:latest 156041424020.dkr.ecr.us-east-1.amazonaws.com/modeller-repo-1f858f9/modeller:latest

            - name: Push Docker image to ECR
              run: |
                  docker push 156041424020.dkr.ecr.us-east-1.amazonaws.com/modeller-repo-1f858f9/modeller:latest

            - name: Install Pulumi
              uses: pulumi/actions@v6
              with:
                  command: up
                  stack-name: dev
              env:
                  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
