name: Test AWS Authentication

on:
    workflow_dispatch:
    issue_comment:
        types: [created]

jobs:
    test-auth:
        # Only run on PR comments that say "test auth"
        if: |
            github.event_name == 'workflow_dispatch' ||
            (github.event.issue.pull_request != null &&
            github.event.comment.body == 'test auth')
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Debug Info
              run: |
                  echo "Repository: ${{ github.repository }}"
                  echo "Actor: ${{ github.actor }}"
                  echo "Event Name: ${{ github.event_name }}"
                  echo "Ref: ${{ github.ref }}"

            - name: Verify OIDC Token
              run: |
                  curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq
              env:
                  ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
                  ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}

            - name: Authenticate with AWS
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  role-to-assume: arn:aws:iam::156041424020:role/github-oidc-role-86262ca
                  aws-region: us-east-1
                  role-duration-seconds: 900
                  debug-logging: true

            - name: Test AWS Access
              run: |
                  echo "Testing get-caller-identity..."
                  aws sts get-caller-identity --debug

                  echo "Testing role assumption directly..."
                  aws sts assume-role-with-web-identity \
                    --role-arn arn:aws:iam::156041424020:role/github-oidc-role-86262ca \
                    --role-session-name "GitHubActions" \
                    --web-identity-token "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                    --debug
